Repository openstack-k8s-operators/tcib, pull requests merged in 2023-07, with the labels that each got.

#54 Install glanceclient
  container-images/tcib/base/openstackclient/openstackclient.yaml
Labels: lgtm, approved

#52 Add tool to expose yum_update ansible tasks
  roles/modify_container_image/tasks/yum_update_buildah.yml
  roles/modify_container_image/templates/yum_update.sh.j2
  setup.cfg
  tcib/client/container_image.py
  tcib/client/utils.py
Labels: lgtm, approved, ok-to-test

#57 Drop tcib_variables in favor of image_config
  AUTHORS
  tcib/client/container_image.py
Labels: approved

#59 Add option to parse a profile to tempestconf
  container-images/tcib/base/os/tempest/run_tempest.sh
Labels: lgtm, approved

#58 Ironic: remove unused ironic-inspector-client
  container-images/tcib/base/os/ironic-base/ironic-conductor/ironic-conductor.yaml
Labels: lgtm, approved

#60 Drop tcib build_containers role
  AUTHORS
  ci/playbooks/build_zed_containers.yaml
  ci/roles/build_containers/defaults/main.yaml
  ci/roles/build_containers/tasks/install.yaml
  ci/roles/build_containers/tasks/main.yaml
  ci/roles/build_containers/templates/build_containers.sh.j2
  ci/roles/build_containers/vars/main.yaml
  roles/build_containers
Labels: lgtm, approved
