Repository openstack-k8s-operators/tcib, pull requests merged in 2023-12, with the labels that each got.

#109 Temporarly skip openstack-tempest-all
  container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml
Labels: lgtm, approved

#110 Add Manila Plugin to tempest extras
  container-images/tcib/base/os/tempest/tempest-extras/tempest-extras.yaml
Labels: lgtm, approved

#107 Revert "Revert "Merge pull request #96 from lpiwowar/feature/tempest-…
  container-images/tcib/base/os/tempest/run_tempest.sh
Labels: lgtm, approved, ok-to-test

#112 Remove temporary skip of tempest-all package
  container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml
Labels: lgtm, approved

#111 [placement] remove example httpd /etc/httpd/conf.d/00-placement-api.conf
  container-images/tcib/base/os/placement-api/placement-api.yaml
Labels: lgtm, approved

#113 [tempest-extras]Add barbican tempest plugin
  container-images/tcib/base/os/tempest/tempest-extras/tempest-extras.yaml
Labels: lgtm, approved

#116 [README]Document container tag to tcib commit match
  README.md
Labels: lgtm, approved

#114 Adding some env variables to Tobiko image
  container-images/tcib/base/os/tobiko/run_tobiko.sh
  container-images/tcib/base/os/tobiko/tobiko.yaml
Labels: lgtm, approved

#103 Support external tempest plugins
  container-images/tcib/base/os/tempest/run_tempest.sh
Labels: question, lgtm, approved, ok-to-test

#117 Run tempest images built in content-provider job
  zuul.d/job.yaml
Labels: lgtm, approved
